---
- name: package installations
  hosts: environment
  any_errors_fatal: true
  become: yes
  roles:
  - role: site.common
  - role: site.mqtt
  #--------------------------------------------------------------------------------
  # NTLM proxy
  #--------------------------------------------------------------------------------
  #- role: site.cntlm
