- name: Pinging to verify Ansible itself...
  hosts: environment
  gather_facts: no
  tasks:
  - ping:


- name: Setup Ansible pre-requisites...
  hosts: environment
  any_errors_fatal: true
  become: yes
  gather_facts: no
  roles:
  - python